import type { AuditResult, CaseRecord, Claim, DocumentReference, MedicalDocument, MedicalEvent, Medication } from "./types";
import type { Fact } from "./types";
import { buildRelationships, detectChanges, detectEvidenceGaps, detectMedicationConflicts, detectNumericConflicts, detectStatusConflicts, resolveDocumentReferences } from "./evidence-engine";

export function buildCaseAudit(caseRecord: CaseRecord, documents: MedicalDocument[], facts: Fact[] = [], claims:Claim[]=[],medications:Medication[]=[],documentReferences:DocumentReference[]=[],events:MedicalEvent[]=[]): AuditResult {
  const resolvedReferences=resolveDocumentReferences(documentReferences,documents),changes=detectChanges(facts), conflicts=[...detectNumericConflicts(facts),...detectStatusConflicts(facts),...detectMedicationConflicts(medications)].map((conflict,index)=>({...conflict,displayId:`CONFLICT #${String(index+1).padStart(2,"0")}`})),gaps=detectEvidenceGaps(claims,facts,documents,resolvedReferences),relationships=buildRelationships(facts,claims,changes,conflicts,gaps),traceable=[...facts,...claims,...medications,...events,...resolvedReferences].filter((item)=>item.sourceDocumentId&&item.sourcePage&&item.sourceText).length,totalEvidence=facts.length+claims.length+medications.length+events.length+resolvedReferences.length;
  return {
    caseRecord, documents, facts, claims, medications, events, documentReferences:resolvedReferences, changes, conflicts, gaps, relationships,
    timeline: documents.map((document) => { const clinicalDate=document.clinicalDates?.find((item)=>item.type==="specimen_collection")??document.clinicalDates?.find((item)=>item.type==="encounter")??document.clinicalDates?.find((item)=>item.type==="report")??document.clinicalDates?.[0],documentClaim=claims.find((claim)=>claim.sourceDocumentId===document.id); return { id: `event:${document.id}`, date: clinicalDate?.value??null, title: document.name, document, detail: documentClaim?.claim??document.processingNote ?? (document.processingStatus === "PROCESSED" ? "Adaptive extraction completed." : "Uploaded source registered; structured extraction has not completed."), factIds: facts.filter((fact)=>fact.sourceDocumentId===document.id).map((fact)=>fact.id), flags: document.processingStatus === "REQUIRES_REVIEW" ? ["REQUIRES_REVIEW"] : [] }; }),
    metrics: { documents: documents.length, facts: facts.length, claims: claims.length, medications:medications.length,events:events.length,references:resolvedReferences.length,changes: changes.length, conflicts: conflicts.length, gaps: gaps.length, unresolved: conflicts.length + gaps.length + documents.filter((document) => document.processingStatus === "REQUIRES_REVIEW").length, traceability: totalEvidence ? Math.round(traceable/totalEvidence*100) : documents.length ? 100 : 0 },
  };
}
